name: tests
on: push
jobs:
  checkout:
      runs-on: ubuntu-latest
      steps:
        - name: checkout_repo
          uses: actions/checkout@v3
  unittest:
    runs-on: ubuntu-latest
    steps: 
      - name: unittest
        run: python3 -m unittest test_main_unit.py
  pytest:
    needs: unittest
    runs-on: ubuntu-latest
    steps: 
      - name: pytest
        run: pytest -o log_cli=true --log-level=INFO test_main_pytest.py
      
